version: '3'
services:
  load_balancer:
    build: .
    tty: true
    ports:
      - "11638:11638"
      - "11636:11636"

  nemo_a:
    image: nginx:1.17.6
    # Mapping port so you can visit directly in browser. This is not used by NGINX proxying and can be removed
    # Docker create app_1 DNS entry in internal network for cross-container communication
    ports:
      - "8080:80"
    volumes:
      - ./apps/nemo_a.html:/usr/share/nginx/html/index.html:ro
  nemo_b:
    image: nginx:1.17.6-alpine
    ports:
      - "8081:80"
    volumes:
      - ./apps/nemo_b.html:/usr/share/nginx/html/index.html:ro

  grandma_a:
    image: nginx:1.17.6-alpine
    volumes:
      - ./apps/grandma_a.html:/usr/share/nginx/html/index.html:ro
  grandma_b:
    image: nginx:1.17.6-alpine
    volumes:
      - ./apps/grandma_b.html:/usr/share/nginx/html/index.html:ro
