version: '3'
services:
  load_balancer:
    build: .
    volumes:
      - ./load_balancer:/etc/nginx
    ports:
      - "11638:11638"
      - "11636:11636"

  app1_a:
    image: nginx:1.17.6
    # Mapping port so you can visit directly in browser. This is not used by NGINX proxying and can be removed
    # Docker creates a 'app1_a' DNS entry in internal network for cross-container communication
    ports:
      - "8080:80"
    volumes:
      - ./apps/app1_a.html:/usr/share/nginx/html/index.html:ro
  app1_b:
    image: nginx:1.17.6-alpine
    ports:
      - "8081:80"
    volumes:
      - ./apps/app1_b.html:/usr/share/nginx/html/index.html:ro

  app2_a:
    image: nginx:1.17.6-alpine
    ports:
      - "8082:80"
    volumes:
      - ./apps/app2_a.html:/usr/share/nginx/html/index.html:ro
  app2_b:
    image: nginx:1.17.6-alpine
    ports:
      - "8083:80"
    volumes:
      - ./apps/app2_b.html:/usr/share/nginx/html/index.html:ro
