version: '3'
services:
  load_balancer:
    image: nginx:1.17.6-alpine
    ports:
      - "5000:80"
    volumes:
      - ./load_balancer/nginx.conf:/etc/nginx/nginx.conf

  app_1:
    image: nginx:1.17.6-alpine
    # Mapping port so you can visit directly in browser. This is not used by NGINX proxying and can be removed
    # Docker create app_1 DNS entry in internal network for cross-container communication
    ports:
      - "8080:80"
    volumes:
      - ./app1:/usr/share/nginx/html
  app_2:
    image: nginx:1.17.6-alpine
    ports:
      - "8081:80"
    volumes:
      - ./app2:/usr/share/nginx/html
